version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://bitwarden.click2eat.es"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
    ports:
      - "9000:80"
      - "9012:3012"
    volumes:
      - /opt/bitwarden/vw-data:/data
