---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: wata

  tasks:
    - name: Creating user "bitwarden" with admin access
      user:
        name: bitwarden
        state: present
        password: "{{ BITWARDEN_USER_PASSWORD }}"
        groups: sudo
        append: yes


    - name: Cloning git
      git:
        repo: "https://github.com/alejandrofm98/config-servidores.git"
        dest: "/home/proyectos/config-servidores"
        force: true

    - name: Downloading bitwarden volume from drive using python script
      become: yes
      become_method: "sudo"
      ansible.builtin.script:
        cmd: ../copias_seguridad/copias_seguridad.py download bitwarden
        executable: /usr/bin/python3

    - name: Copying google drive api key
      ansible.builtin.unarchive:
        src:  ../copias_seguridad/key_account_service.json
        dest: /

    - name: Copying volume
      ansible.builtin.unarchive:
        src: /home/ubuntu/bitwarden_volume.tar.gz
        dest: /
        remote_src: yes

    - name: Create crontab backup.
      become: yes
      become_method: sudo
      cron:
        name: "Ansible: backup bitwarden"
        minute: "0"
        hour: "8"
        job: "python3 /home/proyectos/config-servidores/configuraciones/copias_seguridad/copias_seguridad.py backup bitwarden"
        state: present

    - name: Run `docker-compose down`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/bitwarden
        state: absent
      register: output


    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/bitwarden
        build: true
      register: output

    - name: Copy nginx conf file
      ansible.builtin.copy:
        src: /home/proyectos/config-servidores/configuraciones/bitwarden/bitwarden.click2eat.es
        dest: /etc/nginx/sites-available/bitwarden.click2eat.es
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link from sites-available to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/bitwarden.click2eat.es
        dest: /etc/nginx/sites-enabled/bitwarden.click2eat.es
        owner: root
        group: root
        state: link

    - name: Checking Nginx configuration
      ansible.builtin.shell: sudo nginx -t

    - name: Restarting Nginx service
      ansible.builtin.shell: sudo service nginx restart
