---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: wata
  tasks:
    - name: Creating user "filebrowser" with admin access
      user:
        name: filebrowser
        state: present
        password:  "{{ FILEBROWSER_USER_PASSWORD }}"
        groups: sudo
        append: yes

    - name: Cloning git
      git:
        repo: "https://github.com/alejandrofm98/config-servidores.git"
        dest: "/home/proyectos/config-servidores"
        force: true


#    - name: Copying maquinas file
#      ansible.builtin.copy:
#        src: maquinas
#        dest: /home/proyectos/config-servidores/configuraciones/ansible/maquinas

    - name: Downloading filebrowser volume using python script
      become: yes
      become_method: "sudo"
      ansible.builtin.script:
        cmd: /home/gnome/Escritorio/config-servidores/configuraciones/copias_seguridad/copias_seguridad.py download filebrowser
        executable: /usr/bin/python3

    - name: Copying filebrowser volume
      ansible.builtin.unarchive:
        src: /home/ubuntu/filebrowser_volume.tar.gz
        dest: /
        remote_src: yes

    - name: Create crontab backup.
      become: yes
      become_method: sudo
      cron:
        name: "Ansible: backup filebrowser"
        minute: "0"
        hour: "8"
        job: "python3 /home/proyectos/config-servidores/configuraciones/copias_seguridad/copias_seguridad.py backup filebrowser"
        state: present

    - name: Run `docker-compose down`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/filebrowser
        state: absent
      register: output

    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/filebrowser
        build: true
      register: output

    - name: Copy nginx conf file
      ansible.builtin.copy:
        src: /home/proyectos/config-servidores/configuraciones/filebrowser/filebrowser.click2eat.es
        dest: /etc/nginx/sites-available/filebrowser.click2eat.es
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link from sites-available to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/filebrowser.click2eat.es
        dest: /etc/nginx/sites-enabled/filebrowser.click2eat.es
        owner: root
        group: root
        state: link

    - name: Checking Nginx configuration
      ansible.builtin.shell: sudo nginx -t

    - name: Restarting Nginx service
      ansible.builtin.shell: sudo service nginx restart
