---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: desarrollo
  tasks:
    - name: Creating user "github_actions" with admin access
      user:
        name: github_actions
        state: present
        password:  "{{ FILEBROWSER_USER_PASSWORD }}"
        groups: sudo
        append: yes

    - name: Cloning git
      git:
        repo: "https://github.com/alejandrofm98/config-servidores.git"
        dest: "/home/proyectos/config-servidores"
        force: true

    - name: Copying .env
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/github/.env
        dest: /home/proyectos/config-servidores/configuraciones/github/.env

    - name: Run `docker-compose down`
      community.docker.docker_compose_v2:
        project_src: /home/proyectos/config-servidores/configuraciones/github
        state: absent
      register: output

    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: /home/proyectos/config-servidores/configuraciones/github
        build: always
      register: output
