---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: wasta

  tasks:
    - name: Creating user "jenkins" with admin access
      user:
        name: jenkins
        state: present
        password:  "{{ JENKINS_USER_PASSWORD }}"
        groups: sudo
        append: yes


    - name: Cloning git
      git:
        repo: "https://github.com/alejandrofm98/config-servidores.git"
        dest: "/home/proyectos/config-servidores"
        force: true

    - name: Downloading Jenkins volume from drive using python script
      become: yes
      become_method: "sudo"
      ansible.builtin.script:
        cmd: ~/IdeaProjects/config-servidores/configuraciones/copias_seguridad/copias_seguridad.py download jenkins
        executable: /usr/bin/python3

    - name: Copiando volumen
      ansible.builtin.unarchive:
        src: /home/ubuntu/jenkins_volume.tar.gz
        dest: /
        remote_src: yes

    - name: Create crontab backup.
      become: yes
      become_method: sudo
      cron:
        name: "Ansible: backup jenkins"
        minute: "0"
        hour: "8"
        job: "python3 /home/proyectos/config-servidores/configuraciones/copias_seguridad/copias_seguridad.py backup jenkins"
        state: present

    - name: Copying ssh config
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/sshKeys/
        dest: ~/.ssh/

    - name: Run `docker-compose down`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/jenkins
        state: absent
      register: output


    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/jenkins
        build: true
      register: output

    - name: Copy nginx conf file
      ansible.builtin.copy:
        src: /home/proyectos/config-servidores/configuraciones/jenkins/jenkins.click2eat.es
        dest: /etc/nginx/sites-available/jenkins.click2eat.es
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link from sites-available to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/jenkins.click2eat.es
        dest: /etc/nginx/sites-enabled/jenkins.click2eat.es
        owner: root
        group: root
        state: link

    - name: Checking Nginx configuration
      ansible.builtin.shell: sudo nginx -t

    - name: Restarting Nginx service
      ansible.builtin.shell: sudo service nginx restart

