---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: "{{entorno}}"
  tasks:
    - name: Actualizamos dependencias
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Actualizamos aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Install VIM and nano
      apt:
        name: nano
        state: present
        update_cache: yes

    - name: Comprueba existe vim
      apt:
        name: vim
        state: present
        update_cache: yes

    - name: Install docker dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create "docker" group
      group:
        name: "docker"
        state: present

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-aarch64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
#
    - name: Install SSHFS
      apt:
        name: sshfs
        state: present
        update_cache: true

    - name: Copying ssh config to root
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/sshKeys/
        dest: ~/.ssh/
        force: true

    - name: Copying ssh config to ubuntu
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/sshKeys/
        dest: /home/ubuntu/.ssh/
        force: true

    - name: Copying config-servidores
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/aplicacion
        dest: /home/ubuntu/proyectos

    - name: Renaming .env
      ansible.builtin.file:
        src: /home/ubuntu/proyectos/aplicacion/{{env}}
        dest: /home/ubuntu/proyectos/aplicacion/.env
        state: hard
        force: yes

    - name: Install nginx and certbot
      apt:
        pkg:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: latest
        update_cache: true

    - name: Copying certificates
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/ssl_certs/
        dest: /etc/letsencrypt/live


    - name: Configuring certbot
      become: yes
      become_method: "sudo"
      ansible.builtin.command: echo -e "1" certbot certonly --cert-name click2eat.es --reuse-key --cert-path /etc/letsencrypt/live/click2eat.es/cert.pem --key-path /etc/letsencrypt/live/click2eat.es/privkey.pem --fullchain-path /etc/letsencrypt/live/click2eat.es/fullchain.pem --chain-path /etc/letsencrypt/live/click2eat.es/chain.pem



    - name: Copy nginx conf file
      ansible.builtin.copy:
        src: /home/alejandro/IdeaProjects/config-servidores/configuraciones/aplicacion/{{fichero_nginx}}
        dest: /etc/nginx/sites-available/{{fichero_nginx}}
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link from sites-available to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{fichero_nginx}}
        dest: /etc/nginx/sites-enabled/{{fichero_nginx}}
        owner: root
        group: root
        state: link

    - name: Checking Nginx configuration
      ansible.builtin.shell: sudo nginx -t

    - name: Restarting Nginx service
      ansible.builtin.shell: sudo service nginx restart


