---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: utilidades
  tasks:
    - name: Creating user "sonar" with admin access
      user:
        name: sonar
        state: present
        password:  "{{ SONAR_USER_PASSWORD }}"
        groups: sudo,docker
        append: yes


    - name: Copying sonar folder
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/sonar/
        dest: /home/ubuntu/sonar/

    - name: Run `docker-compose down`
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/sonar/
        state: absent
      register: output

    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/sonar/
        build: always
      register: output

    - name: Copy nginx conf file
      ansible.builtin.copy:
        src:  /home/ubuntu/sonar/sonar.click2eat.es
        dest: /etc/nginx/sites-available/sonar.click2eat.es
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link from sites-available to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/sonar.click2eat.es
        dest: /etc/nginx/sites-enabled/sonar.click2eat.es
        owner: root
        group: root
        state: link

    - name: Checking Nginx configuration
      ansible.builtin.shell: sudo nginx -t

#    Solo es necesario ejecutar 1 vez
#    - name: Open ports iptable
#      ansible.builtin.shell:
#        sudo iptables -I INPUT  -m state --state NEW -p tcp --dport 443 -j ACCEPT &&
#        sudo iptables -I OUTPUT  -m state --state NEW -p tcp --dport 443 -j ACCEPT &&
#        sudo iptables -I INPUT  -m state --state NEW -p tcp --dport 80 -j ACCEPT &&
#        sudo iptables -I OUTPUT  -m state --state NEW -p tcp --dport 80 -j ACCEPT

    - name: Restarting Nginx service
      ansible.builtin.shell: sudo service nginx restart
