---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: wasta
  tasks:
    - name: Creating user "sonar" with admin access
      user:
        name: sonar
        state: present
        password:  "{{ SONAR_USER_PASSWORD }}"
        groups: sudo,docker
        append: yes

    - name: Cloning git
      git:
        repo: "https://github.com/alejandrofm98/config-servidores.git"
        dest: "/home/proyectos/config-servidores"
        force: true

    - name: Copying .env
      ansible.builtin.copy:
        src: ~/IdeaProjects/config-servidores/configuraciones/sonar/.env
        dest: /home/proyectos/config-servidores/configuraciones/sonar/.env

    - name: Run `docker-compose down`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/sonar
        state: absent
      register: output

    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /home/proyectos/config-servidores/configuraciones/sonar
        build: true
      register: output

    - name: Copy nginx conf file
      ansible.builtin.copy:
        src: /home/proyectos/config-servidores/configuraciones/sonar/sonar.click2eat.es
        dest: /etc/nginx/sites-available/sonar.click2eat.es
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link from sites-available to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/sonar.click2eat.es
        dest: /etc/nginx/sites-enabled/sonar.click2eat.es
        owner: root
        group: root
        state: link

    - name: Checking Nginx configuration
      ansible.builtin.shell: sudo nginx -t

    - name: Restarting Nginx service
      ansible.builtin.shell: sudo service nginx restart
