version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    restart: always
    container_name: filebrowser
    user: "${UID}:${GID}"
    volumes:
      - /home/filebrowser/filebrowser_configuration/config/.filebrowser.json:/.filebrowser.json
      - /home/filebrowser/filebrowser_configuration/database/filebrowser.db:/database/filebrowser.db
      - /mnt/filebrowser/des:/mnt/des
      - /mnt/filebrowser/pro:/mnt/pro

    ports:
      - 8200:8200
