version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    restart: always
    container_name: filebrowser
    user: "${UID}:${GID}"
    volumes:
      - /home/filebrowser/filebrowser_configuration/config/filebrowser.json:/.filebrowser.json #Change to match your directory
      - /home/filebrowser/filebrowser_configuration/database/filebrowser.db:/database/filebrowser.db #Change to match your directory

    ports:
      - 8200:8200
