# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name walerike.com www.walerike.com;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name walerike.com www.walerike.com;

    ssl_certificate /etc/letsencrypt/live/walerike.com/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/walerike.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Root del frontend Angular
    root /usr/share/nginx/html/browser;
    index index.html;

    # IMPORTANTE: Las locations más específicas van PRIMERO

    # Ruta para Certbot challenge
    location ~ ^/.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Angular SPA: redirige todo a index.html - VA AL FINAL
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name walactv.walerike.com;

    ssl_certificate /etc/letsencrypt/live/walerike.com/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/walerike.com/privkey.pem;

    root /var/www/walactv;

     # Archivos estáticos
    location ~* \.apk$ {
        add_header Content-Type "application/vnd.android.package-archive";
        add_header Content-Disposition "attachment";
        try_files $uri =404;
    }

    location ~* \.ipa$ {
        add_header Content-Type "application/octet-stream";
        add_header Content-Disposition "attachment";
        try_files $uri =404;
    }

    location ~* \.(json|plist)$ {
        add_header Content-Type "application/json";
        try_files $uri =404;
    }

    location / {
        proxy_pass http://walactv-proxificaurl:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

