version: "3.3"

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    build:
      dockerfile: jenkins.dockerfile
      context: .
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - /home/jenkins/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
