version: '3.8'

services:
  runner:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: '2.317.0'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
      ENTORNO: ${ENTORNO}
