version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    restart: always
    tty: true
    sysctls:
      - vm.max_map_count=262144
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL:-sonar}
      SONAR_JDBC_USERNAME: ${POSTGRES_USER:-sonar}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD:-sonar}
    ports:
      - "9001:9000"
    volumes:
      - /home/sonar/conf:/opt/sonarqube/conf
      - /home/sonar/etc:/etc/
      - /home/sonar/data:/opt/sonarqube/data
      - /home/sonar/extensions:/opt/sonarqube/extensions
      - /home/sonar/logs:/opt/sonarqube/logs
      - /home/sonar/temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sonar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sonar}
      POSTGRES_DB: ${POSTGRES_DB:-sonar}
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
