version: "3.9"
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'    
    expose:
      - '3306'
    volumes:
      - java-db:/var/lib/mysql
    
  java:
      image: java
      build:
        dockerfile: dockerfile
      volumes:
      - /home/ubuntu/desplegar/restaurantqr:/app
      ports:
        - "8080:8080"
      depends_on: 
        db:
          condition: service_started
volumes:
  java-db:

