version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot-etc:/etc/letsencrypt
#      - ./certbot-www:/var/www/certbot
#    entrypoint: >
#      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
#      --email joseluji223@gmail.com --agree-tos --no-eff-email
#      -d jlacdev.es -d www.jlacdev.es"



networks:
  nginx-net:
    external: true
